## Generate random nrd-PIP instances I and random element beta 
## for two-element representation 
## of the ideal I and test whether this beta commutes with
## one of the solutions to the nrd-PIP instance


#################################
## Operations in the algebra A ##
#################################

## elements of A are represented by vectors of K^4: x = (a,b,c,d) meaning a + b*i + c*j + d*(ij)

def nrd(x):
    # x = [a,b,s,d] in K^4
    # return a^2+b^2+c^2+d^2
    return sum([y^2 for y in x])
    
def bar_A(x):
    # returns bar(x) (in A)
    return vector(K,[x[0],-x[1],-x[2],-x[3]])
    
def mult_A(x,y):
    # returns x*y
    return vector(K,[x[0]*y[0]-x[1]*y[1]-x[2]*y[2]-x[3]*y[3], x[0]*y[1]+x[1]*y[0]+x[2]*y[3]-x[3]*y[2], x[0]*y[2]+x[2]*y[0]-x[1]*y[3]+x[3]*y[1], x[0]*y[3]+x[3]*y[0]+x[1]*y[2]-x[2]*y[1]])
    
def inv_A(x):
    # returns x^(-1)
    # Warning: the output may not be in OK anymore
    return nrd(x)^(-1)*vector(K,bar_A(x))
    
    
##########################################################
## Sampling the ideal and its 2 elements representation ##
##########################################################
def random_prime_z():
    # sample a random z = [a,b,c,d] in OK^4 until N(z) is prime
    while True:
        z = [OK.random_element() for _ in range(4)]
        q = nrd(z)
        q_Z = q.norm()
        if q_Z.is_prime():
            return vector(OK,z)
                        
def random_z():
    # sample a random z = [a,b,c,d] in OK^4 arbitrary
    return vector(OK,[OK.random_element() for _ in range(4)])
    
            
def basis_ideal_OK(z):
    ## returns an OK_basis of the ideal generated by z
    [a,b,c,d] = z
    B = Matrix(OK,[[a,b,c,d],[-b,a,d,-c],[-c,-d,a,b],[-d,c,-b,a]])
    return B

 
def random_beta(z, Normz = None, verbose=True):
    #sample a random element in the ideal generated by z
    # and makes sure that this is not a multiple of nrd(z)
    if Normz is None:
        Normz = nrd(z).norm()
    while True:
        v = [OK.random_element() for _ in range(4)]
        beta = mult_A(z,v)
        Nbeta = nrd(beta).norm()
        if gcd(Nbeta/(Normz),Normz) == 1:
            return beta
        else:
            if verbose:
                print("resampling beta")
          
# from my previous tests, it should be true that such (beta,nrd(z)) generates the ideal z*O

    
###########################################################
### Computing all the solutions of the nrd-PIP instance ###
###########################################################

def root_unity_in_K2():
    ## returns the expression of t (the m-th root of unity in L) as a vector of K^2 such that t = t1 + i*t2, and output the pair [t1,t2]
    list_v = []
    for j in range(2^(k-1)): ## degree of L (cyclo field)
        v = []
        for i in range(2^(k-2)):
            v += [phi(t0^i)[j]]
        for i in range(2^(k-2)):
            if j-2^(k-2) >= 0:
                v += [phi(t0^i)[j-2^(k-2)]]
            else:
                v += [-phi(t0^i)[j+2^(k-2)]]
        list_v += [v]
    M = matrix(QQ,list_v)
    y = vector(QQ,[0,1]+[0]*(2^(k-1)-2))
    res = M^(-1)*y
    x1 = sum([res[i]*t0^i for i in range(2^(k-2))])
    x2 = sum([res[i+2^(k-2)]*t0^i for i in range(2^(k-2))])
    x = vector(K,[x1,x2,0,0])
    
    ## checking that x is indeed a root of unity as wanted
    z = x
    for l in range(k):
        if z == vector(K,[1,0,0,0]):
            print("warning, x is a ", 2^l, "th root of unity (not ", 2^k, ")")
        z = mult_A(z,z)
    if z != vector(K,[1,0,0,0]):
        print(z)
        print("warning, x is not a ", 2^k, "th root of unity")
    return x
    

def all_solutions_z(z, zeta):
    ## computes the list of all solutions to the nrd-PIP instance
    ## zeta is the output of the function root_unity_in_K2()
    list_z = []
    tmp_z = z
    for i in range(2^k):
        list_z += [tmp_z]
        list_z += [mult_A(tmp_z, vector(K,[0,0,1,0]))]
        tmp_z = mult_A(tmp_z,zeta)
    assert(tmp_z == z) ## verify that we looped back to z)
    return list_z
    

########################################################
## Testing whether s (or another solution to nrd-PIP) ##
## commutes with beta                                 ##
########################################################    

def test_permutation(list_z,beta):
    ## test whether beta commutes with one of the solution z to the nrd-PIP equation (which is implied by beta being in the good field)
    for z1 in list_z:
        if mult_A(z1,beta) == mult_A(beta,z1):
            print(beta, " permutes with ", z1)
            return True
    return False
        
        
def multi_tests(Nz, Nbeta=1, z_is_prime=False, verbose=False):
    ## Nz*Nbeta random tests, with Nz different choices of z, and Nbeta different choices of beta for each z
    
    ## preparing a file to write the results in
    if z_is_prime == True:
        file_name = 'results/success_probability_prime_'+str(2^(k))+'_'+str(Nz)+'_'+str(Nbeta)+'.txt'
    else:
        file_name = 'results/success_probability_'+str(2^(k))+'_'+str(Nz)+'_'+str(Nbeta)+'.txt'
    o = open(file_name,'w')
    o.write("Cyclotomic field of conductor: "+str(2^k))
    o.write("\nNumber of z tested: "+str(Nz))
    o.write("\nNumber of beta per z: "+str(Nbeta))
    o.write("\nSuccess probability per z: [")
    
    ## generating global objects
    zeta = root_unity_in_K2()
    l_nb_success = []
    nb_tests = 0
    for tmpz in range(Nz):
        ## sampling z and creating useful objects
        if z_is_prime:
            z = random_prime_z()
        else:
            z = random_z()
        Normz = nrd(z).norm() ## norm of z
        list_z = all_solutions_z(z,zeta) ## list of all solutions
        nb_success_z = 0
        ## sampling multiple random beta for a given z
        for tmpbeta in range(Nbeta):
            try:
                beta = random_beta(z, Normz = Normz, verbose=verbose)
                if test_permutation(list_z,beta):
                    nb_success_z += 1
            except KeyboardInterrupt:
                return
            except:
                print("an error occured when trying to generate beta for z = ", z)
            nb_tests += 1
        l_nb_success += [nb_success_z]
        o.write(str(RR(nb_success_z/Nbeta))+",")
            
    ## writing final results in a file
    nb_success = sum(l_nb_success)
    o.write("]")
    o.write("\nTotal number of tests: "+str(nb_tests))
    o.write("\nTotal number of successes: "+str(nb_success))
    o.write("\nTotal success probability: "+str(RR(nb_success/nb_tests)))
    return RR(nb_success/nb_tests)
    
#########################
### Running the tests ###
#########################
k = 4
L.<t> = CyclotomicField(2^k)
(K,phi) = L.maximal_totally_real_subfield()
t0 = K.gen()
OL = L.maximal_order()
OK = K.maximal_order()


#multi_tests(100)
